; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 9600


[env:door_ecu]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 9600
build_flags = -DDOOR_ECU

[env:ac_ecu]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 9600
build_flags = -DAC_ECU

[env:lights_ecu]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 9600
build_flags = -DLIGHTS_ECU

[env:heating_ecu]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 9600
build_flags = -DHEATING_ECU

[env:default]

; ; ---- OTA SETTINGS ----
; upload_protocol = espota
; upload_port = 192.168.0.102   ; <-- ESP32 IP (shown in Serial)
; upload_flags =
;     --auth=OTAupdate123      ; must match ArduinoOTA password